
CREATE PLUGGABLE DATABASE mon_26983_pacific_pharmacy_db
  ADMIN USER pacific IDENTIFIED BY "Pacific"
  FILE_NAME_CONVERT = (
    'C:\USERS\PACIF\DOWNLOADS\ORADATA\ORCL\PDBSEED\',
    'C:\USERS\PACIF\DOWNLOADS\ORADATA\ORCL\MON_26983_PACIFIC_PHARMACY_DB\'
  );

-- Open and save state
ALTER PLUGGABLE DATABASE mon_26983_pacific_pharmacy_db OPEN;
ALTER PLUGGABLE DATABASE mon_26983_pacific_pharmacy_db SAVE STATE;

-- Connect session to the new PDB
ALTER SESSION SET CONTAINER = mon_26983_pacific_pharmacy_db;

-- Create application user
CREATE USER pharmacy_user IDENTIFIED BY pharmacy_pass
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

-- Grant privileges
GRANT CONNECT, RESOURCE, DBA TO pharmacy_user;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO pharmacy_user;
GRANT CREATE TRIGGER, CREATE PROCEDURE, CREATE VIEW TO pharmacy_user;
